# this game will be asking the user to guess the number (from 1 to 100) generated by the model
# if successfully guessed, the game will end
# else the program will assist the user how far is the guess.

import random

target = random.randint(1, 100)

while True:
    userGuess = input("Guess the number (1 - 100) or Quit(press: Q) :")
    if(userGuess.upper() == "Q"):
        break

    userGuess = int(userGuess)
    if(userGuess == target):
        print("Sucess: Correct Guess!!")
        break
    elif(userGuess > target):
        print("guess is bigger. make a smaller guess")
    else:
        print("guess is smaller. make a bigger guess")

print("Thanks for contributing\n"
        "-----GAME OVER------\n"
        "Hope to see you again")